In [2]:
'''NumPy (Numerical Python) is a Python library used for:

Fast mathematical operations
Working with arrays (better than lists)
Foundation of ML, Data Science, Pandas, etc.

👉 Core idea:
Replace slow Python loops with fast array operations'''


'NumPy (Numerical Python) is a Python library used for:\n\nFast mathematical operations\nWorking with arrays (better than lists)\nFoundation of ML, Data Science, Pandas, etc.\n\n👉 Core idea:\nReplace slow Python loops with fast array operations'

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np


In [5]:
l = [1, 2, 3]    # Python List ---Stores different objects in memory 2) Slow (each element is separate)

In [6]:
ar = np.array([1, 2, 3]) #Stores continuous block of memory 2)All elements same type 3)Very fast

In [7]:
type(ar)

numpy.ndarray

In [8]:
ar = np.array([[1,2,3],[4,5,6]])   #shape = (2,3) , ndim = 2 ,size = 6
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(ar.ndim)    # dimensions
print(ar.shape)   # structure
print(ar.size)    # total elements
print(ar.dtype)   # data type
print(ar.itemsize) # bytes per element
print(ar.nbytes)  # total memory

2
(2, 3)
6
int64
8
48


In [10]:
import numpy as np                      # import NumPy library
c = [2, 3, 4]                          # Python list
type(c)                                # check type → list
arr = np.asarray(c)                    # convert list to NumPy array
arr                                    # output → array([2, 3, 4])
arr.shape                              # shape of array → (3,) (1D array)
arr + 1                                # element-wise addition → array([3, 4, 5])
arr * 2                                # element-wise multiplication → array([4, 6, 8])
c + [1]                                # list concatenation → [2, 3, 4, 1] (NOT addition)
# c + 1                                # ❌ error → cannot add int directly to list

[2, 3, 4, 1]

In [11]:
import numpy as np                      # import NumPy
c = [2, 3, 4]                          # Python list
b = np.matrix(c)                       # convert list into NumPy matrix (always 2D)
b                                      # output → matrix([[2, 3, 4]])
b.shape                                # shape → (1, 3) (1 row, 3 columns)
type(b)                                # type → numpy.matrix
b.T                                    # transpose → matrix([[2],
                                       #               [3],
                                       #               [4]])
b * b.T                                # matrix multiplication → 1x3 * 3x1 → matrix([[29]])
np.asarray(b)    # convert matrix back to array → array([[2, 3, 4]])


x = np.asanyarray(b)                   # convert using asanyarray (keeps subclass)

x

matrix([[2, 3, 4]])

In [12]:
a= np.array(c)
a


array([2, 3, 4])

In [13]:
c = a

In [14]:
c


array([2, 3, 4])

In [15]:
a

array([2, 3, 4])

In [16]:
c[1] = 100

In [17]:
a

array([  2, 100,   4])

In [18]:
import numpy as np                      # import NumPy
c = [2, 3, 4]                          # original Python list
a = np.array(c)                        # create NumPy array from list
a, c                                   # both values → (array([2, 3, 4]), [2, 3, 4])
c[1] = 100                             # modify list at index 1
c                                      # → [2, 100, 4]
a                                      # → array([2, 3, 4]) (UNCHANGED)

array([2, 3, 4])

In [19]:
import numpy as np                      # import NumPy

c = [2, 3, 4]                          # Python list

a = np.array(c)                        # create NumPy array → array([2, 3, 4])

d = np.copy(a)                         # create a deep copy of array a

d                                      # → array([2, 3, 4])

d[0] = 100                             # modify copied array

d                                      # → array([100, 3, 4])

a                                      # → array([2, 3, 4]) (UNCHANGED)

array([2, 3, 4])

In [20]:
import numpy as np                                # import NumPy
def func(i, j):                                   # define function (takes indices)
    return i + j                                   # operation using indices


arr = np.fromfunction(func, (3, 3), dtype=int)    # create 3x3 array using function
arr                                               # output →
                                                  # array([[0, 1, 2],
                                                  #        [1, 2, 3],
                                                  #        [2, 3, 4]])

# example 2 ====
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)   # multiplication

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [21]:
gen = (i*i for i in range(5))               # generator → 0,1,4,9,16
arr = np.fromiter(gen, dtype=int)           # convert to array
arr                                         # → array([ 0,  1,  4,  9, 16])

array([ 0,  1,  4,  9, 16])

In [22]:
s = "1 2 3 4 5"   
arr = np.fromstring(s, dtype=int, sep=' ')      # convert string → NumPy array
arr                                             # → array([1, 2, 3, 4, 5]) 

array([1, 2, 3, 4, 5])

In [23]:
a = np.array([1, 2, 3.5])
print(a)

[1.  2.  3.5]


In [24]:
import numpy as np                              # import NumPy

arr1 = np.arange(5)                             # start=0, stop=5, step=1 (default)

arr1                                            # → array([0, 1, 2, 3, 4])

arr2 = np.arange(2, 10)                         # start=2, stop=10, step=1

arr2                                            # → array([2, 3, 4, 5, 6, 7, 8, 9])

arr3 = np.arange(1, 10, 2)                      # start=1, stop=10, step=2

arr3                                            # → array([1, 3, 5, 7, 9])

arr4 = np.arange(0, 1, 0.2)                     # float step

arr4                                            # → array([0. , 0.2, 0.4, 0.6, 0.8])

array([0. , 0.2, 0.4, 0.6, 0.8])

In [25]:
np.linspace(0, 1, 10)                          # safer

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [26]:
import numpy as np                              # import NumPy

arr1 = np.zeros(5)                              # 1D array of 5 zeros

arr1                                            # → array([0., 0., 0., 0., 0.])

arr2 = np.zeros((2, 3))                         # 2D array (2 rows, 3 columns)

arr2                                            # → array([[0., 0., 0.],
                                                 #        [0., 0., 0.]])

arr3 = np.zeros((3, 3), dtype=int)              # integer zeros instead of float

arr3                                            # → array([[0, 0, 0],
                                                 #        [0, 0, 0],
                                                 #        [0, 0, 0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
#In NumPy, np.ones() is used to create an array filled entirely with the value 1.
import numpy as np                              # import NumPy

arr1 = np.ones(5)                               # 1D array of 5 ones

arr1                                            # → array([1., 1., 1., 1., 1.])

arr2 = np.ones((2, 3))                          # 2D array (2 rows, 3 columns)

arr2                                            # → array([[1., 1., 1.],
                                                 #        [1., 1., 1.]])

arr3 = np.ones((3, 3,2), dtype=int)               # integer ones

arr3                                            # → array([[1, 1],
                                                 #        [1, 1],
                                                 #        [1, 1]])

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [28]:
'''In NumPy, np.empty() creates an array without initializing values.

👉 That means:

It allocates memory, but does NOT fill it with 0 or 1'''
import numpy as np                              # import NumPy

arr1 = np.empty(5)                              # create 1D array (uninitialized)

arr1                                            # → random values (NOT zeros)

arr2 = np.empty((2, 3))                         # 2D array

arr2                                            # → random garbage values

arr3 = np.empty((2,2), dtype=int)               # integer type

arr3                                            # → random integers

array([[4596373779694328218, 4600877379321698714],
       [4603579539098121012, 4605380978949069210]])

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
import numpy as np                              # import NumPy

I = np.eye(3)                                   # create 3x3 identity matrix

I                                                # →
                                                 # [[1. 0. 0.]
                                                 #  [0. 1. 0.]
                                                 #  [0. 0. 1.]]

A = np.array([[2, 3, 4],                        # sample matrix (real data)
              [5, 6, 7],
              [8, 9, 10]])

np.dot(A, I)                                    # multiply with identity

# Output → same as A (identity doesn't change matrix)

In [ ]:
#  np.logspace(0, 3, 4) ==== interanally 10^0, 10^1, 10^2, 10^3
import numpy as np                              # import NumPy

arr1 = np.logspace(0, 3, 4)                     # 10^0 to 10^3 → 4 values

arr1                                            # → [   1.   10.  100. 1000.]

arr2 = np.logspace(1, 2, 5)                     # 10^1 to 10^2 → 5 values

arr2                                            # → [ 10. , 17.78, 31.62, 56.23, 100.]

arr3 = np.logspace(0, 2, 5, base=2)             # base 2 instead of 10

arr3                                            # → [1., 2., 4., 8., 16.]


In [30]:
import numpy as np                                  # import NumPy

np.random.rand(3)                                   # random numbers (0 to 1) → 1D

np.random.rand(2, 3)                                # 2x3 matrix → values between 0 and 1

np.random.randn(3)                                  # random numbers (normal distribution)

np.random.randint(1, 10, (2, 3))                    # random integers from 1 to 9

np.random.random((2,2))                             # same as rand()

np.random.choice([10, 20, 30, 40], size=3)          # random selection from list

np.random.seed(42)                                  # fix randomness (important)

np.random.rand(3)                                   # same output every time after seed

array([0.37454012, 0.95071431, 0.73199394])

In [36]:
import numpy as np                              # import NumPy

a = np.arange(6)                                # create array → [0,1,2,3,4,5]

a                                               # → array([0, 1, 2, 3, 4, 5])

b = a.reshape(2, 3)                             # reshape into 2 rows, 3 columns

b                                               # →
                                                # [[0 1 2]
                                                #  [3 4 5]]

c = a.reshape(3, 2)                             # reshape into 3 rows, 2 columns

c                                               # →
                                                # [[0 1]
                                                #  [2 3]
                                                #  [4 5]]

d = a.reshape(1, 6)                             # row vector
d

#e = a.reshape(6, 1)                             # column vector

#f = a.reshape(-1, 2)                            # auto-calculate rows

#g = a.reshape(2, -1)                            # auto-calculate columns

array([[0, 1, 2, 3, 4, 5]])

In [32]:
b[1][1]

np.int64(4)

In [35]:
import numpy as np                      # import NumPy

c = np.array([[1, 2, 3],                # 2D array (example)
              [4, 5, 6],
              [7, 8, 9]])

c[1:3, 1]                              

array([5, 8])

In [37]:
arr = np.random.randint(0, 100, (5,5))
arr

array([[60, 20, 82, 86, 74],
       [74, 87, 99, 23,  2],
       [21, 52,  1, 87, 29],
       [37,  1, 63, 59, 20],
       [32, 75, 57, 21, 88]], dtype=int32)

In [38]:
arr[arr>50]

array([60, 82, 86, 74, 74, 87, 99, 52, 87, 63, 59, 75, 57, 88],
      dtype=int32)

In [39]:
arr[2:4,[1,2]] # data from the table 2 nd row to 3 rd row and 1 and 2 column

array([[52,  1],
       [ 1, 63]], dtype=int32)

In [40]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [41]:
arr1

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 2]], dtype=int32)

In [42]:
arr2

array([[1, 2, 2],
       [1, 2, 1],
       [2, 1, 2]], dtype=int32)

In [43]:
arr1 +arr2

array([[2, 3, 3],
       [2, 4, 3],
       [4, 3, 4]], dtype=int32)

In [44]:
arr1- arr2

array([[ 0, -1, -1],
       [ 0,  0,  1],
       [ 0,  1,  0]], dtype=int32)

In [45]:
arr1 / arr2

array([[1. , 0.5, 0.5],
       [1. , 1. , 2. ],
       [1. , 2. , 1. ]])

In [46]:
arr1 *arr2 # its not matrix multiplication is diff

array([[1, 2, 2],
       [1, 4, 2],
       [4, 2, 4]], dtype=int32)

In [47]:
np.dot(arr1, arr2)  # correct logic

array([[ 4,  5,  5],
       [ 7,  8,  8],
       [ 8, 10, 10]], dtype=int32)

In [48]:
# OR

arr1 @ arr2 

array([[ 4,  5,  5],
       [ 7,  8,  8],
       [ 8, 10, 10]], dtype=int32)

In [49]:
 arr1+100

array([[101, 101, 101],
       [101, 102, 102],
       [102, 102, 102]], dtype=int32)

In [50]:
arr1**2

array([[1, 1, 1],
       [1, 4, 4],
       [4, 4, 4]], dtype=int32)

In [53]:
# Broadcasting = Automatically expanding smaller arrays to match bigger arrays for operations
X = np.array([[1,2,3],
              [4,5,6]])

bias = np.array([1,1,1])

X + bias

array([[2, 3, 4],
       [5, 6, 7]])

In [52]:
import numpy as np                                  # import NumPy

a = np.array([1, 2, 3])                             # 1D array

b = 5                                               # scalar

a + b                                               # broadcasting → add 5 to each element
                                                    # → array([6, 7, 8])


# -----------------------------------------

A = np.array([[1, 2, 3],                            # 2x3 matrix
              [4, 5, 6]])

B = np.array([10, 20, 30])                          # 1D array

A + B                                               # broadcasting across rows
                                                    # → [[11 22 33]
                                                    #    [14 25 36]]


# -----------------------------------------

C = np.array([[1],                                  # column vector (2x1)
              [2]])

D = np.array([10, 20, 30])                          # row vector (3,)

C + D                                               # full broadcasting → 2x3 result
                                                    # → [[11 21 31]
                                                    #    [12 22 32]]

array([[11, 21, 31],
       [12, 22, 32]])

In [54]:
import numpy as np                                      # import NumPy

# ------------------ TRANSPOSE ------------------

A = np.array([[1, 2, 3],                                # 2x3 matrix
              [4, 5, 6]])

A.T                                                     # transpose → rows ↔ columns
                                                        # [[1 4]
                                                        #  [2 5]
                                                        #  [3 6]]


# ------------------ SQRT ------------------

arr = np.array([1, 4, 9, 16])

np.sqrt(arr)                                            # square root (element-wise)
                                                        # → [1. 2. 3. 4.]


# ------------------ LOG10 ------------------

arr2 = np.array([1, 10, 100, 1000])

np.log10(arr2)                                          # log base 10 (element-wise)
                                                        # → [0. 1. 2. 3.]


array([0., 1., 2., 3.])